service: auctions
app: auctions

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221

functions:
  createAction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction


